# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
      - build

# workflow tasks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 18 # The Go version to download (if necessary) and use.
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Run Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o rest_auth_proxy .
