name: Merged PR
on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, closed]
jobs:
  build-project:
    if: ((github.event.action == 'closed' && github.event.pull_request.merged == true))
    strategy:
      matrix:
        go: [1.18]
        os: [ubuntu]
    name: Build golang application
    runs-on: ${{ matrix.os}}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - run: go build -o raproxy-${{ matrix.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: raproxy-${{ matrix.os }}
          path: ./
  release-project:
    if: ((github.event.action == 'closed' && github.event.pull_request.merged == true))
    strategy:
      matrix:
        #os: [macos, windows, ubuntu]
        os: [ubuntu]
    name: Release golang application
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download applications
        uses: actions/download-artifact@v3
      - run: ls -la 
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: "v1.0.${{ github.event.pull_request.number }}"
          allowUpdates: true
          artifacts: "**/raproxy-*"
